### ISSUE TITLE
下载出错('文本没有匹配上字段：字段名为\'name\'......后面好像就是网页的全部内容

### ISSUE THREAD

**Issue by narcissu3rd** [FateTrial/FateTrial_JMdownloader#20]
报错内容：
 [22:18:51] [Core] [INFO] [core.event_bus:50]: [aiocqhttp] Narcissu/3: /jm 222868
 [22:18:52] [Core] [INFO] [respond.stage:211]: AstrBot -> Narcissu/: 开始下载 222868了喵
[2025-05-01 22:18:52] [MainThread]:【plugin.invoke】调用插件: [login]
[2025-05-01 22:18:52] [MainThread]:【html】https://18comic.vip/login
[2025-05-01 22:18:53] [MainThread]:【plugin.login】登录成功
[2025-05-01 22:18:53] [asyncio_1]:【html】https://18comic.vip/album/222868
[2025-05-01 22:18:54] [asyncio_1]:【dler.exception】JmDownloader Exit with exception: (<class 'jmcomic.jm_exception.RegularNotMatchException'>, RegularNotMatchException('文本没有匹配上字段：字段名为\'name\'，pattern: [re.compile(\'<h1 class="book-name" id="book-name">([\\\\s\\\\S]*?)</h1>\')]响应文本过长(len=372075)，不打印', {'html': '<!doctype html>\n<html lang="en">\n<head>\n    <meta name="google" content="notranslate">\n\n    <meta name="juicyads-site-verification" content="9dc45d0c989efd2d562bc0bfa0ae960b">\n    <meta name="exoclick-site-verification" content="02a42f90b0f54accd3b5a8b44e3c2c54">\n    <meta name="trafficjunky-site-verification" content="vtt10qy00"/>\n    <meta name="ero_verify" content="c55bde9f8536c9020bbbdee53a9ceee9"/>\n    <meta name="linkbuxverifycode" content="32dc01246faccb7f5b3cad5016dd5033" />\n\n        \n        <meta property="og:site_name" content="禁漫天堂">\n    <meta property="og:title" content="[白杨汉化组] [矢印キー (星名めいと)] 呪いの指輪でゲームオーバー 記憶改変集 Comics - 禁漫天堂">\n  

.......后面省略37w字

**Comment by fuyueqi1** [comment]
更新jmcomic库即可

**Comment by Jackxwb** [comment]
已尝试更新`jmcomic`至`2.5.38`版本，使用本插件依旧报错
```
[14:46:47] [Core] [INFO] [core.event_bus:50]: [aiocqhttp] 匿名: /jm下载 1160395  
 [14:46:47] [Core] [INFO] [respond.stage:211]: AstrBot -> 匿名: [引用消息] 🤖开始下载本子 1160395，请稍候...  
 [14:46:49] [Core] [INFO] [respond.stage:211]: AstrBot -> 匿名: [引用消息] 🤖下载出错: 文本没有匹配上字段：字段名为'name'，pattern: [re.compile('<h2 class="book-name" id="book-name"[^>]*?>([\\s\\S]*?)</h2>')]响应文本过长(len=370929)，不打印  
```
已尝试重启`AstrBot`依旧报错

进入Docker容器，使用命令行执行`jmcomic 1160395`，可正常下载

**Comment by fuyueqi1** [comment]
经测试，使用命令行执行 `jmcomic xxx` 操作时可以从api端正常获取图片，而本插件是使用html端。单独测试从html端下载都出现了上述报错。可以尝试将`option.yml` 中的`impl`项和`domain`项注释或删除，以使用库默认的下载方式。

**Comment by Jackxwb** [comment]
> 经测试，使用命令行执行 `jmcomic xxx` 操作时可以从api端正常获取图片，而本插件是使用html端。单独测试从html端下载都出现了上述报错。可以尝试将`option.yml` 中的`impl`项和`domain`项注释或删除，以使用库默认的下载方式。

谢谢，配置文件更换成官网文档里面的，改用`api`模式就可以下载了
```
client:
  # impl: 客户端实现类，不配置默认会使用JmModuleConfig.DEFAULT_CLIENT_IMPL
  # 可配置:
  #  html - 表示网页端
  #  api - 表示APP端
  # APP端不限ip兼容性好，网页端限制ip地区但效率高
  # impl: html
  impl: api

  # domain: 域名配置，默认是 []，表示运行时自动获取域名。
  # 可配置特定域名，如下：
  # 程序会先用第一个域名，如果第一个域名重试n次失败，则换下一个域名重试，以此类推。
  domain:
    html:
      - 18comic-uc.vip
      - 18comic-mhws.vip
      - 18comic-uc.cc
      - jmcomic-zzz.one
      - jmcomic-zzz.org
    api:
      - www.jmapiproxyxxx.vip
```
